---
abstract: "Interface to Google's Blogger service"
author:
  - 'Egor Shipovalov <kogdaugodno@gmail.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Blogger
provides:
  WebService::Blogger:
    file: lib/WebService/Blogger.pm
    version: 0.12
  WebService::Blogger::AtomReading:
    file: lib/WebService/Blogger/AtomReading.pm
  WebService::Blogger::Blog:
    file: lib/WebService/Blogger/Blog.pm
  WebService::Blogger::Blog::Entry:
    file: lib/WebService/Blogger/Blog/Entry.pm
requires:
  Any::Moose: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  XML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
