---
abstract: "Interface to Google's Blogger service"
author:
  - 'Egor Shipovalov <kogdaugodno@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Blogger
requires:
  File::stat: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Role: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.15
